import { z } from 'zod';

const optionalStr = z.string().optional().or(z.literal(''));

export const studentFormSchema = z.object({
  admissionNo: z.string().min(1, 'Required'),
  rollNumber: optionalStr,
  firstName: z.string().min(1, 'Required'),
  lastName: z.string().min(1, 'Required'),
  dateOfBirth: z.string().min(1, 'Required'),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER']),
  classId: z.string().min(1, 'Pick a class'),
  sectionId: optionalStr,
  admissionDate: optionalStr,
  bloodGroup: optionalStr,
  nationalId: optionalStr,
  religion: optionalStr,
  nationality: optionalStr,
  email: optionalStr,
  phone: optionalStr,
  address: optionalStr,
  city: optionalStr,
  country: optionalStr,
  studentStatus: optionalStr,
  fatherName: optionalStr,
  fatherCnic: optionalStr,
  fatherPhone: optionalStr,
  fatherEmail: optionalStr,
  fatherOccupation: optionalStr,
  motherName: optionalStr,
  motherCnic: optionalStr,
  motherPhone: optionalStr,
  motherEmail: optionalStr,
  motherOccupation: optionalStr,
  guardianName: optionalStr,
  guardianRelation: optionalStr,
  guardianPhone: optionalStr,
  guardianEmail: optionalStr,
  guardianAddress: optionalStr,
  emergencyContactName: optionalStr,
  emergencyContactPhone: optionalStr,
  previousSchool: optionalStr,
  medicalNotes: optionalStr,
  transportRequired: z.boolean().optional(),
  hostelRequired: z.boolean().optional(),
  remarks: optionalStr,
  isActive: z.enum(['true', 'false']).optional(),
});

export type StudentFormValues = z.infer<typeof studentFormSchema>;

export function studentFormToApi(values: StudentFormValues, includeStatus = false) {
  const body: Record<string, unknown> = {
    admissionNo: values.admissionNo,
    rollNumber: values.rollNumber?.trim() || undefined,
    firstName: values.firstName,
    lastName: values.lastName,
    dateOfBirth: new Date(values.dateOfBirth).toISOString(),
    gender: values.gender,
    classId: values.classId,
    sectionId: values.sectionId?.trim() ? values.sectionId : undefined,
    admissionDate: values.admissionDate?.trim()
      ? new Date(values.admissionDate).toISOString()
      : undefined,
    bloodGroup: values.bloodGroup?.trim() || undefined,
    nationalId: values.nationalId?.trim() || undefined,
    religion: values.religion?.trim() || undefined,
    nationality: values.nationality?.trim() || undefined,
    email: values.email?.trim() || undefined,
    phone: values.phone?.trim() || undefined,
    address: values.address?.trim() || undefined,
    city: values.city?.trim() || undefined,
    country: values.country?.trim() || undefined,
    studentStatus: values.studentStatus?.trim() || undefined,
    fatherName: values.fatherName?.trim() || undefined,
    fatherCnic: values.fatherCnic?.trim() || undefined,
    fatherPhone: values.fatherPhone?.trim() || undefined,
    fatherEmail: values.fatherEmail?.trim() || undefined,
    fatherOccupation: values.fatherOccupation?.trim() || undefined,
    motherName: values.motherName?.trim() || undefined,
    motherCnic: values.motherCnic?.trim() || undefined,
    motherPhone: values.motherPhone?.trim() || undefined,
    motherEmail: values.motherEmail?.trim() || undefined,
    motherOccupation: values.motherOccupation?.trim() || undefined,
    guardianName: values.guardianName?.trim() || undefined,
    guardianRelation: values.guardianRelation?.trim() || undefined,
    guardianPhone: values.guardianPhone?.trim() || undefined,
    guardianEmail: values.guardianEmail?.trim() || undefined,
    guardianAddress: values.guardianAddress?.trim() || undefined,
    emergencyContactName: values.emergencyContactName?.trim() || undefined,
    emergencyContactPhone: values.emergencyContactPhone?.trim() || undefined,
    previousSchool: values.previousSchool?.trim() || undefined,
    medicalNotes: values.medicalNotes?.trim() || undefined,
    transportRequired: values.transportRequired ?? false,
    hostelRequired: values.hostelRequired ?? false,
    remarks: values.remarks?.trim() || undefined,
  };
  if (includeStatus && values.isActive) {
    body.isActive = values.isActive === 'true';
  }
  return body;
}

export function studentRecordToForm(data: Record<string, unknown>): StudentFormValues {
  const sec = data.section as { id?: string } | undefined;
  return {
    admissionNo: String(data.admissionNo ?? ''),
    rollNumber: data.rollNumber != null ? String(data.rollNumber) : '',
    firstName: String(data.firstName ?? ''),
    lastName: String(data.lastName ?? ''),
    dateOfBirth: String(data.dateOfBirth ?? '').slice(0, 10),
    gender: (['MALE', 'FEMALE', 'OTHER'].includes(String(data.gender))
      ? String(data.gender)
      : 'MALE') as StudentFormValues['gender'],
    classId: String(data.classId ?? ''),
    sectionId: sec?.id ? String(sec.id) : '',
    admissionDate: data.admissionDate ? String(data.admissionDate).slice(0, 10) : '',
    bloodGroup: data.bloodGroup != null ? String(data.bloodGroup) : '',
    nationalId: data.nationalId != null ? String(data.nationalId) : '',
    religion: data.religion != null ? String(data.religion) : '',
    nationality: data.nationality != null ? String(data.nationality) : '',
    email: data.email != null ? String(data.email) : '',
    phone: data.phone != null ? String(data.phone) : '',
    address: data.address != null ? String(data.address) : '',
    city: data.city != null ? String(data.city) : '',
    country: data.country != null ? String(data.country) : '',
    studentStatus: data.studentStatus != null ? String(data.studentStatus) : '',
    fatherName: data.fatherName != null ? String(data.fatherName) : '',
    fatherCnic: data.fatherCnic != null ? String(data.fatherCnic) : '',
    fatherPhone: data.fatherPhone != null ? String(data.fatherPhone) : '',
    fatherEmail: data.fatherEmail != null ? String(data.fatherEmail) : '',
    fatherOccupation: data.fatherOccupation != null ? String(data.fatherOccupation) : '',
    motherName: data.motherName != null ? String(data.motherName) : '',
    motherCnic: data.motherCnic != null ? String(data.motherCnic) : '',
    motherPhone: data.motherPhone != null ? String(data.motherPhone) : '',
    motherEmail: data.motherEmail != null ? String(data.motherEmail) : '',
    motherOccupation: data.motherOccupation != null ? String(data.motherOccupation) : '',
    guardianName: data.guardianName != null ? String(data.guardianName) : '',
    guardianRelation: data.guardianRelation != null ? String(data.guardianRelation) : '',
    guardianPhone: data.guardianPhone != null ? String(data.guardianPhone) : '',
    guardianEmail: data.guardianEmail != null ? String(data.guardianEmail) : '',
    guardianAddress: data.guardianAddress != null ? String(data.guardianAddress) : '',
    emergencyContactName: data.emergencyContactName != null ? String(data.emergencyContactName) : '',
    emergencyContactPhone: data.emergencyContactPhone != null ? String(data.emergencyContactPhone) : '',
    previousSchool: data.previousSchool != null ? String(data.previousSchool) : '',
    medicalNotes: data.medicalNotes != null ? String(data.medicalNotes) : '',
    transportRequired: Boolean(data.transportRequired),
    hostelRequired: Boolean(data.hostelRequired),
    remarks: data.remarks != null ? String(data.remarks) : '',
    isActive: data.isActive === false ? 'false' : 'true',
  };
}
